
nope:

raw:
	rm -rf repo/raw
	time ruby rawtc.rb
	#time ruby rawtc.rb
	#time ruby rawtc.rb
	#time ruby rawtc.rb
	#time ruby rawtc.rb
	#time ruby rawtc.rb

batch:
	rm -rf repo/random-people
	time ruby1.9 batch-load-users.rb

gen:
	ruby xampl-gen.rb
	ruby1.9 xampl-gen-191.rb

