
nope:

raw:
	rm -rf repo/raw
	time ruby rawtc.rb
	#time ruby rawtc.rb
	#time ruby rawtc.rb
	#time ruby rawtc.rb
	#time ruby rawtc.rb
	#time ruby rawtc.rb

batch:
	rm -rf repo/random-people
	time ruby batch-load-users.rb

single:
	rm -rf repo/singly-added
	time ruby individually-load-users.rb
