

ccm:
	rm -rf ccm
	mkdir ccm
	#saikuro -c -w 8 -e 13 -o ccm/ -p ./admin/admin.rb -p ./admin/helpers/admin_ui_helper.rb
	saikuro -c -w 8 -e 13 -o ccm/ -p ./xampl.rb -p ./xamplr/exceptions.rb -p ./xamplr/from-xml.rb -p ./xamplr/indexed-array.rb -p ./xamplr/iterator.rb -p ./xamplr/mixins.rb -p ./xamplr/notifications.rb -p ./xamplr/persist-to-xml.rb -p ./xamplr/persistence.rb -p ./xamplr/persister.rb -p ./xamplr/persisters/caches.rb -p ./xamplr/persisters/caching.rb -p ./xamplr/persisters/dumb.rb -p ./xamplr/persisters/filesystem.rb -p ./xamplr/persisters/in-memory.rb -p ./xamplr/persisters/mongo.rb -p ./xamplr/persisters/simple.rb -p ./xamplr/persisters/tokyo-cabinet.rb -p ./xamplr/to-ruby.rb -p ./xamplr/to-xml.rb -p ./xamplr/visitor.rb -p ./xamplr/visitors.rb -p ./xamplr/xampl-module.rb -p ./xamplr/xampl-object-internals.rb -p ./xamplr/xampl-object.rb -p ./xamplr/xampl-persisted-object.rb -p ./xamplr/xml-text.rb -p ./xamplr.rb
