
nope:

raw:
	rm -rf repo
	time ruby rawtc.rb
	#time ruby rawtc.rb
	#time ruby rawtc.rb
	#time ruby rawtc.rb
	#time ruby rawtc.rb
	#time ruby rawtc.rb

batch:
	rm -rf repo
	time ruby batch-load-users.rb

